[2024-08-24T10:08:58.519+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T10:08:58.539+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_air_pollution_data.download_air_pollution_dataset manual__2024-08-24T10:08:55.718077+00:00 [queued]>
[2024-08-24T10:08:58.549+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_air_pollution_data.download_air_pollution_dataset manual__2024-08-24T10:08:55.718077+00:00 [queued]>
[2024-08-24T10:08:58.550+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T10:08:58.564+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): download_air_pollution_dataset> on 2024-08-24 10:08:55.718077+00:00
[2024-08-24T10:08:58.574+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=786) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T10:08:58.578+0000] {standard_task_runner.py:72} INFO - Started process 788 to run task
[2024-08-24T10:08:58.578+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'download_air_pollution_data', 'download_air_pollution_dataset', 'manual__2024-08-24T10:08:55.718077+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/Seoul.py', '--cfg-path', '/tmp/tmpn9ysly96']
[2024-08-24T10:08:58.580+0000] {standard_task_runner.py:105} INFO - Job 115: Subtask download_air_pollution_dataset
[2024-08-24T10:08:58.664+0000] {task_command.py:467} INFO - Running <TaskInstance: download_air_pollution_data.download_air_pollution_dataset manual__2024-08-24T10:08:55.718077+00:00 [running]> on host 94bdab50145e
[2024-08-24T10:08:58.805+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_air_pollution_data' AIRFLOW_CTX_TASK_ID='download_air_pollution_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T10:08:55.718077+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T10:08:55.718077+00:00'
[2024-08-24T10:08:58.809+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-24T10:08:58.809+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-24T10:08:58.810+0000] {logging_mixin.py:190} INFO - Current task name:download_air_pollution_dataset state:running start_date:2024-08-24 10:08:58.540164+00:00
[2024-08-24T10:08:58.811+0000] {logging_mixin.py:190} INFO - Dag name:download_air_pollution_data and current dag run status:running
[2024-08-24T10:08:58.812+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T10:08:58.813+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-24T10:08:58.814+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'kaggle datasets download -d bappekim/air-pollution-in-seoul -p /data --unzip']
[2024-08-24T10:08:58.826+0000] {subprocess.py:86} INFO - Output:
[2024-08-24T10:09:00.888+0000] {subprocess.py:93} INFO - Dataset URL: https://www.kaggle.com/datasets/bappekim/air-pollution-in-seoul
[2024-08-24T10:09:00.889+0000] {subprocess.py:93} INFO - License(s): CC-BY-SA-4.0
[2024-08-24T10:09:00.890+0000] {subprocess.py:93} INFO - Downloading air-pollution-in-seoul.zip to /data
[2024-08-24T10:09:00.891+0000] {subprocess.py:93} INFO -   0%|          | 0.00/19.7M [00:00<?, ?B/s]  0%|          | 0.00/19.7M [00:00<?, ?B/s]
[2024-08-24T10:09:00.891+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-08-24T10:09:00.893+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/kaggle", line 8, in <module>
[2024-08-24T10:09:00.894+0000] {subprocess.py:93} INFO -     sys.exit(main())
[2024-08-24T10:09:00.895+0000] {subprocess.py:93} INFO -              ^^^^^^
[2024-08-24T10:09:00.896+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kaggle/cli.py", line 63, in main
[2024-08-24T10:09:00.897+0000] {subprocess.py:93} INFO -     out = args.func(**command_args)
[2024-08-24T10:09:00.899+0000] {subprocess.py:93} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-24T10:09:00.900+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1586, in dataset_download_cli
[2024-08-24T10:09:00.901+0000] {subprocess.py:93} INFO -     self.dataset_download_files(dataset,
[2024-08-24T10:09:00.902+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1510, in dataset_download_files
[2024-08-24T10:09:00.903+0000] {subprocess.py:93} INFO -     self.download_file(response, outfile, quiet, not force)
[2024-08-24T10:09:00.904+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 1967, in download_file
[2024-08-24T10:09:00.905+0000] {subprocess.py:93} INFO -     with open(outfile, open_mode) as out:
[2024-08-24T10:09:00.906+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-24T10:09:00.907+0000] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/data/air-pollution-in-seoul.zip'
[2024-08-24T10:09:00.946+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-08-24T10:09:00.961+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-24T10:09:00.968+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-24T10:09:00.969+0000] {logging_mixin.py:190} INFO - Task start:2024-08-24 10:08:58.540164+00:00 end:2024-08-24 10:09:00.967365+00:00 duration:2.427201
[2024-08-24T10:09:00.969+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): download_air_pollution_dataset> dag:<DAG: download_air_pollution_data> dagrun:<DagRun download_air_pollution_data @ 2024-08-24 10:08:55.718077+00:00: manual__2024-08-24T10:08:55.718077+00:00, state:running, queued_at: 2024-08-24 10:08:55.740816+00:00. externally triggered: True>
[2024-08-24T10:09:00.970+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-08-24T10:09:00.971+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=download_air_pollution_data, task_id=download_air_pollution_dataset, run_id=manual__2024-08-24T10:08:55.718077+00:00, execution_date=20240824T100855, start_date=20240824T100858, end_date=20240824T100900
[2024-08-24T10:09:00.989+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T10:09:00.990+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 115 for task download_air_pollution_dataset (Bash command failed. The command returned a non-zero exit code 1.; 788)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-24T10:09:01.025+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-24T10:09:01.048+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-24T10:09:01.050+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
