[2024-08-24T14:56:46.189+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T14:56:46.209+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_air_pollution_data.get_seoul_api manual__2024-08-24T14:56:41.604078+00:00 [queued]>
[2024-08-24T14:56:46.217+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_air_pollution_data.get_seoul_api manual__2024-08-24T14:56:41.604078+00:00 [queued]>
[2024-08-24T14:56:46.218+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T14:56:46.231+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_seoul_api> on 2024-08-24 14:56:41.604078+00:00
[2024-08-24T14:56:46.239+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4480) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T14:56:46.240+0000] {standard_task_runner.py:72} INFO - Started process 4484 to run task
[2024-08-24T14:56:46.241+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'download_air_pollution_data', 'get_seoul_api', 'manual__2024-08-24T14:56:41.604078+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/Seoul.py', '--cfg-path', '/tmp/tmp0gua0t4s']
[2024-08-24T14:56:46.242+0000] {standard_task_runner.py:105} INFO - Job 132: Subtask get_seoul_api
[2024-08-24T14:56:46.297+0000] {task_command.py:467} INFO - Running <TaskInstance: download_air_pollution_data.get_seoul_api manual__2024-08-24T14:56:41.604078+00:00 [running]> on host 94bdab50145e
[2024-08-24T14:56:46.405+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_air_pollution_data' AIRFLOW_CTX_TASK_ID='get_seoul_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T14:56:41.604078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T14:56:41.604078+00:00'
[2024-08-24T14:56:46.407+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-24T14:56:46.408+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-24T14:56:46.409+0000] {logging_mixin.py:190} INFO - Current task name:get_seoul_api state:running start_date:2024-08-24 14:56:46.209763+00:00
[2024-08-24T14:56:46.409+0000] {logging_mixin.py:190} INFO - Dag name:download_air_pollution_data and current dag run status:running
[2024-08-24T14:56:46.410+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T14:56:46.749+0000] {Seoul.py:14} INFO - <bound method Response.json of <Response [200]>>
[2024-08-24T14:56:46.752+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul.py", line 16, in _get_seoul_api
    f.write(data)
TypeError: write() argument must be str, not method
[2024-08-24T14:56:46.771+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-24T14:56:46.772+0000] {logging_mixin.py:190} INFO - Task start:2024-08-24 14:56:46.209763+00:00 end:2024-08-24 14:56:46.770599+00:00 duration:0.560836
[2024-08-24T14:56:46.773+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_seoul_api> dag:<DAG: download_air_pollution_data> dagrun:<DagRun download_air_pollution_data @ 2024-08-24 14:56:41.604078+00:00: manual__2024-08-24T14:56:41.604078+00:00, state:running, queued_at: 2024-08-24 14:56:41.631632+00:00. externally triggered: True>
[2024-08-24T14:56:46.773+0000] {logging_mixin.py:190} INFO - Failure caused by write() argument must be str, not method
[2024-08-24T14:56:46.774+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=download_air_pollution_data, task_id=get_seoul_api, run_id=manual__2024-08-24T14:56:41.604078+00:00, execution_date=20240824T145641, start_date=20240824T145646, end_date=20240824T145646
[2024-08-24T14:56:46.790+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T14:56:46.791+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 132 for task get_seoul_api (write() argument must be str, not method; 4484)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul.py", line 16, in _get_seoul_api
    f.write(data)
TypeError: write() argument must be str, not method
[2024-08-24T14:56:46.835+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-24T14:56:46.860+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-24T14:56:46.865+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
