[2024-08-24T08:46:23.686+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T08:46:23.708+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_air_pollution_data.download_air_pollution_dataset manual__2024-08-24T08:46:20.821558+00:00 [queued]>
[2024-08-24T08:46:23.719+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_air_pollution_data.download_air_pollution_dataset manual__2024-08-24T08:46:20.821558+00:00 [queued]>
[2024-08-24T08:46:23.719+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T08:46:23.737+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): download_air_pollution_dataset> on 2024-08-24 08:46:20.821558+00:00
[2024-08-24T08:46:23.744+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1009) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T08:46:23.746+0000] {standard_task_runner.py:72} INFO - Started process 1011 to run task
[2024-08-24T08:46:23.746+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'download_air_pollution_data', 'download_air_pollution_dataset', 'manual__2024-08-24T08:46:20.821558+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/Seoul.py', '--cfg-path', '/tmp/tmp90tbvlpw']
[2024-08-24T08:46:23.748+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask download_air_pollution_dataset
[2024-08-24T08:46:23.808+0000] {task_command.py:467} INFO - Running <TaskInstance: download_air_pollution_data.download_air_pollution_dataset manual__2024-08-24T08:46:20.821558+00:00 [running]> on host a253ea3f3033
[2024-08-24T08:46:23.909+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_air_pollution_data' AIRFLOW_CTX_TASK_ID='download_air_pollution_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T08:46:20.821558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T08:46:20.821558+00:00'
[2024-08-24T08:46:23.911+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-24T08:46:23.911+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-24T08:46:23.912+0000] {logging_mixin.py:190} INFO - Current task name:download_air_pollution_dataset state:running start_date:2024-08-24 08:46:23.709529+00:00
[2024-08-24T08:46:23.913+0000] {logging_mixin.py:190} INFO - Dag name:download_air_pollution_data and current dag run status:running
[2024-08-24T08:46:23.914+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T08:46:23.915+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-24T08:46:23.917+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'kaggle datasets download -d bappekim/air-pollution-in-seoul -p /path/to/download/folder --unzip']
[2024-08-24T08:46:23.928+0000] {subprocess.py:86} INFO - Output:
[2024-08-24T08:46:23.931+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: kaggle: command not found
[2024-08-24T08:46:23.933+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-08-24T08:46:23.947+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-08-24T08:46:23.954+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-24T08:46:23.955+0000] {logging_mixin.py:190} INFO - Task start:2024-08-24 08:46:23.709529+00:00 end:2024-08-24 08:46:23.953809+00:00 duration:0.24428
[2024-08-24T08:46:23.956+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): download_air_pollution_dataset> dag:<DAG: download_air_pollution_data> dagrun:<DagRun download_air_pollution_data @ 2024-08-24 08:46:20.821558+00:00: manual__2024-08-24T08:46:20.821558+00:00, state:running, queued_at: 2024-08-24 08:46:20.872359+00:00. externally triggered: True>
[2024-08-24T08:46:23.957+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2024-08-24T08:46:23.957+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=download_air_pollution_data, task_id=download_air_pollution_dataset, run_id=manual__2024-08-24T08:46:20.821558+00:00, execution_date=20240824T084620, start_date=20240824T084623, end_date=20240824T084623
[2024-08-24T08:46:23.974+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T08:46:23.975+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 101 for task download_air_pollution_dataset (Bash command failed. The command returned a non-zero exit code 127.; 1011)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-08-24T08:46:24.013+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-24T08:46:24.035+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-24T08:46:24.037+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
