[2024-08-26T10:45:23.294+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T10:45:23.321+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark.geo_map_plot manual__2024-08-26T10:45:11.503978+00:00 [queued]>
[2024-08-26T10:45:23.333+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark.geo_map_plot manual__2024-08-26T10:45:11.503978+00:00 [queued]>
[2024-08-26T10:45:23.334+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-26T10:45:23.359+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): geo_map_plot> on 2024-08-26 10:45:11.503978+00:00
[2024-08-26T10:45:23.380+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=627) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-26T10:45:23.383+0000] {standard_task_runner.py:72} INFO - Started process 659 to run task
[2024-08-26T10:45:23.389+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Spark', 'geo_map_plot', 'manual__2024-08-26T10:45:11.503978+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/Seoul_spark.py', '--cfg-path', '/tmp/tmp96g5pqwa']
[2024-08-26T10:45:23.392+0000] {standard_task_runner.py:105} INFO - Job 207: Subtask geo_map_plot
[2024-08-26T10:45:23.621+0000] {task_command.py:467} INFO - Running <TaskInstance: Spark.geo_map_plot manual__2024-08-26T10:45:11.503978+00:00 [running]> on host 94bdab50145e
[2024-08-26T10:45:23.758+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark' AIRFLOW_CTX_TASK_ID='geo_map_plot' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T10:45:11.503978+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-26T10:45:11.503978+00:00'
[2024-08-26T10:45:23.762+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-26T10:45:23.764+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-26T10:45:23.765+0000] {logging_mixin.py:190} INFO - Current task name:geo_map_plot state:running start_date:2024-08-26 10:45:23.322429+00:00
[2024-08-26T10:45:23.766+0000] {logging_mixin.py:190} INFO - Dag name:Spark and current dag run status:running
[2024-08-26T10:45:23.771+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T10:45:24.528+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul_spark.py", line 78, in _geomerge_plot
    spark = SparkSession.builder.appName('spark').getOrCreate()
           ^^^^^^^^^^^^
NameError: name 'SparkSession' is not defined
[2024-08-26T10:45:24.559+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-26T10:45:24.560+0000] {logging_mixin.py:190} INFO - Task start:2024-08-26 10:45:23.322429+00:00 end:2024-08-26 10:45:24.558127+00:00 duration:1.235698
[2024-08-26T10:45:24.562+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): geo_map_plot> dag:<DAG: Spark> dagrun:<DagRun Spark @ 2024-08-26 10:45:11.503978+00:00: manual__2024-08-26T10:45:11.503978+00:00, state:running, queued_at: 2024-08-26 10:45:11.631181+00:00. externally triggered: True>
[2024-08-26T10:45:24.563+0000] {logging_mixin.py:190} INFO - Failure caused by name 'SparkSession' is not defined
[2024-08-26T10:45:24.564+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Spark, task_id=geo_map_plot, run_id=manual__2024-08-26T10:45:11.503978+00:00, execution_date=20240826T104511, start_date=20240826T104523, end_date=20240826T104524
[2024-08-26T10:45:24.591+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T10:45:24.592+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 207 for task geo_map_plot (name 'SparkSession' is not defined; 659)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Seoul_spark.py", line 78, in _geomerge_plot
    spark = SparkSession.builder.appName('spark').getOrCreate()
           ^^^^^^^^^^^^
NameError: name 'SparkSession' is not defined
[2024-08-26T10:45:24.652+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-26T10:45:24.699+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T10:45:24.709+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
